version: "3"
services:
  app:
    image: localhost:5000/dashboard-graphs
    container_name: dashboard-graphs
    build:
      context: .
    depends_on:
      - gridengine
    #   - mysql
    #   - minio
    #   - mailhog
    # networks:
    #   - proxy
    #   - private
    expose:
      - "8080"
    ports: 
      - "8080:8080"
  gridengine:
    image: localhost:5000/dashboard-graphs
    ports:
      - "3001:3001"
    expose:
      - "3001"
    command: ["node", "./gridengine.js"]
  tickets:
    image: localhost:5000/dashboard-graphs
    ports:
      - "3018:3018"
    expose:
      - "3000"
    command: ["node", "./RSSparse.js"]
  weather:
    image: localhost:5000/dashboard-graphs
    ports:
      - "3002:3002"
    expose:
      - "3002"
    command: ["/app/refreshWeather.sh"]
  cors_proxy:
    image: localhost:5000/dashboard-graphs
    ports:
      - "8111:8111"
    expose:
      - "8111"
    command: ["node","./cors_proxy.js"]

    
  

